
server:
  port: 8081
  servlet:
    context-path: /interni-sp

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: INFO
    org.opensaml.xmlsec: TRACE

spring:
#  application:
#    name: ciaone

  security:
    saml2:
      relyingparty:
        registration:
          internilogs:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.crt"
            identityprovider:
              verification:
                credentials:
                  - certificate-location: "classpath:credentials/idpcert.crt"
              entity-id: http://host.docker.internal:8081/interni-sp/saml2/service-provider-metadata/internilogs
              singlesignon:
                sign-request: false
      #          url: http://host.docker.internal:8081/interni-sp/login/saml2/sso/internilogs
     #           url: http://localhost:8083/auth/realms/master/protocol/saml
                url: http://localhost:8080/simplesaml/saml2/idp/SSOService.php
              #metadata-uri: http://localhost:8083/auth/realms/master/protocol/saml/descriptor
                metadata-uri: http://localhost:8080/simplesaml/saml2/idp/metadata.php
              #verification.credentials: